version: "3.2"
services:
  multi-chat:
    image: multi-chat:latest
    build:
      # Build an image from the Dockerfile in the current directory
      context: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: dev
      PORT: 8080
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: eu-central-1